name = "NTWorld 11"
author = "NTUSER"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a6b4b2315bc6351c0c94c0778fe19b43517b3a1f2b80dfbfe739da5b3d56297a"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
