name = "NTWorld 11"
author = "NTUSER"
version = "11.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ad116a09ae67220c40e6bb369c15f089b1abd9357623819a5af30b0c7405ce38"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.244"
