name = "NTWorld 11"
author = "NTUSER"
version = "11.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "68b25a62f66c373cbb9d6e20fdb87c4a45770ddb40d1b3824f64f2586da843a9"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.252"
